services:
  vanilla-pp-bot:
    image: vanilla-pp-bot:latest
    pull_policy: never
    container_name: vanilla-pp-bot
    user: "1000:1000"
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./python-bot/config.yml:/app/config.yml:ro
      - ./python-bot/data:/data
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      TZ: "Europe/Minsk"
